/**
 * Bundles src/client.jsx into client.js, a classic script that self-registers
 * with DSH's client module loader. Only platform seed modules stay external
 * (they resolve through the loader's `require`); xterm and its CSS inline.
 */
import { build } from 'esbuild'

await build({
  entryPoints: ['src/client.jsx'],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'chrome120',
  outfile: 'client.js',
  jsx: 'transform',
  jsxFactory: 'React.createElement',
  jsxFragment: 'React.Fragment',
  loader: { '.css': 'text' },
  external: [
    'react',
    'react/jsx-runtime',
    'react-dom',
    'react-dom/client',
    '@deepseek-ai/*',
  ],
  banner: {
    js: [
      '/* dsh-terminal-button client bundle — generated by build.mjs, do not edit. */',
      "window.__ModuleLoader__.load({",
      "  id: 'dsh-terminal-button',",
      '  factory: (require) => {',
      '    var module = { exports: {} };',
      '    var exports = module.exports;',
    ].join('\n'),
  },
  footer: {
    js: ['    return module.exports;', '  },', '});'].join('\n'),
  },
})

console.log('built client.js')
